In [ ]:
#a Импортируйте библиотеку NumPy
import numpy as np
a = np.array ([1,2,3])
print (a)

[1 2 3]


# New Section

In [ ]:
#b.Создайте массив из 10 нулей
import numpy as np
f=np.zeros(10)
print(f)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#c.Создать массив из 10 единиц
f=np.ones(10)
print(f)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#d.Создать массив из 10 пятерок
array=np.ones(10)*5
print(array)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
#e.Создать массив из целых чисел от 10 до 50
d=np.arange(10,51)
print(d)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
#f.Создать массив из четных чисел от 10 до 50
k= np.arange(10,51,2)
print(k)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
#g.Создать матрицу 3х3 с числами от 0 до 8
z=np.arange(0,9)
z_2d = z.reshape(3, 3)
print(z_2d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#h.Создать единичную матрицу 3x3
h = np.eye(3)
print(h)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#i.Используйте NumPy для генерации случайного числа от 0 до 1
x=np.random.random(1)[0]
print(x)

0.8976063468020694


In [ ]:
#j.Используйте NumPy для генерации массива из 25 случайных чисел,взятых из стандартного нормального распределения
i= np.random.rand(25)
print(i)

[0.58119692 0.49996962 0.68966347 0.0087943  0.60450625 0.27769532
 0.11383093 0.90801909 0.96190116 0.53607667 0.23736998 0.97213231
 0.65875384 0.96254237 0.9051189  0.16342346 0.89542469 0.90089304
 0.52161057 0.24782356 0.31889757 0.02020283 0.50549492 0.55795718
 0.29394507]


In [ ]:
#k.Создайте следующую матрицу используя функции библиотеки NumPy
k=np.linspace(0.01,1.,100).reshape(10,10)
print(k)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [ ]:
#I.Дана стартовая матрица (обязательно запустите код ниже в вашемрешении!).
mat = np.arange(1,26).reshape(5,5)
print(mat)
print('l =' , mat[2:, 1:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
l = [[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
#m.Написать код обращения к элементу который вернет значение  20 изстартовой матрицы задачи l
mat = np.arange(1,26).reshape(5,5)
ar = mat[mat==20]
print(ar)
     

[20]


In [ ]:
#n.Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже
mat = np.arange(1,26).reshape(5,5)
print('j=',  mat[0:3,1].reshape(3,1))

j= [[ 2]
 [ 7]
 [12]]


In [ ]:
#o.Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже
arr=np.arange(1,26).reshape(5,5)
temp=arr[4,:]
print(temp)

[21 22 23 24 25]


In [ ]:
#p.Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже
mat=np.arange(1,26).reshape(5,5)
temp=mat[3:0,4:4]
print(temp)

[]


In [ ]:
#q.Получить сумму всех значений в стартовой матрице mat
import numpy as np
mat=np.arange(1,26).reshape(5,5)
print(mat.sum())

325


In [ ]:

#r.Получить стандартное отклонение в стартовой матрице mat
import numpy as np
mat=np.arange(1,26).reshape(5,5)
print(mat.std())

7.211102550927978


In [ ]:
#s.Получить сумму значений в колонках в стартовой матрице mat
import numpy as np
mat=np.arange(1,26).reshape(5,5)
t=mat[[0,1,2,3,4],0]
n=mat[[0,1,2,3,4],1]
q=mat[[0,1,2,3,4],2]
g=mat[[0,1,2,3,4],3]
l=mat[[0,1,2,3,4],4]
print(t.sum(), n.sum(), q.sum(), g.sum(), l.sum())

55 60 65 70 75
